### ISSUE TITLE
% in args of puppetlint maker expanded with file path 

### ISSUE THREAD

**Issue by stanleyz** [neomake/neomake#1069]
% in `'args': ['--log-format', '"%{path}:%{line}:%{column}:%{kind}:[%{check}] %{message}"']` replaced with relative file path because of #991 

To reproduce:

1. create a simple puppet file with warning/errors

```
class test {
  $a = 'hello'
  notify { "hello $a": }
}
```

2. Run Neomake puppetlint and then open location list, you will see the lines in the list similar as 

```
Downloads/test.pp{path}:Downloads/test.pp{line}:Downloads/test.pp{column}:Downloads/test.pp{kind}:[Downloads/test.pp{check}] Downloads/test.pp{message}}
Downloads/test.pp{path}:Downloads/test.pp{line}:Downloads/test.pp{column}:Downloads/test.pp{kind}:[Downloads/test.pp{check}] Downloads/test.pp{message}}
```

Solution:

replace % in the args with %% as explained in #991 ?

**Comment by blueyed** [comment]
I think we should fix `neomake#utils#ExpandArgs` to not expand % before curly braces.
@tweekmonster ?

**Comment by tweekmonster** [comment]
@blueyed I'm a little conflicted with #1070 

Being practical it makes sense because I can't think of a case where `%{}` should expand to `path{}`.

Being pragmatic, the solution is to use `%%` instead of `%` in the puppet maker.  It's a simpler fix that doesn't change the meaning of `%` and continues to match how `:!` works.

I don't want to approve/disapprove because I tend to overthink these small details.

On an unrelated note, I just realized that #991 didn't update the docs.

**Comment by blueyed** [comment]
@tweekmonster 
Agreed, thanks for arguing about it.
Created https://github.com/neomake/neomake/pull/1073 to fix it.
