### ISSUE TITLE
chaining project makers

### ISSUE THREAD

**Issue by stfl** [neomake/neomake#1135]
Is it possible to chain project makers together?

I have a few makers set up for different projects and subprojects I'd like to have them depend on each other or something like that..
like in a Makefile..

or to run multiple commands from a single maker?
or to run multiple makers with a single command. like :Neomake! maker1 maker2 maker_install

Thanks for the feedback

**Comment by blueyed** [comment]
You can use the `serialize` feature.

```
:let g:neomake_serialize = 1
:Neomake! maker1 maker2 maker_install
```

There is also `g:neomake_serialize_abort_on_error` (although that is probably not well-defined yet - IIRC it will kick in for non-zero return values, although some linters would return 0, but add error entries etc).

You might not want to set `g:neomake_serialize` globally though, but e.g. configure it for your makers explicitly:
```
let g:neomake_maker1_serialize = 1
```

There was some discussion already about having flags with the Neomake(!) command, so that you could use `:Neomake! -serialize maker1 maker2 maker3` (and it would configure them all with `serialize = 1` for this run).. (https://github.com/neomake/neomake/issues/589)

**Comment by blueyed** [comment]
Hope that helped, and assuming it to be answered.

**Comment by stfl** [comment]
so finally got to the point in my project to actually make use of this.. thank you.. works perfectly 👍
