### ISSUE TITLE
NeomakeSh and errorformat

### ISSUE THREAD

**Issue by markwoodhall** [neomake/neomake#1138]
Hi, firstly, thanks so much for Neomake. I use it everyday and love it. 

This isn't a bug so I've not filled in all the information in the issue template. 

At the moment I'm just trying to find some information and guidance. I'm in the process of adding Neomake support to the vim-test plugin, which offers such functionality as running tests for the current file, the suite, and the nearest test to the cursor. vim-test has a number of strategies it uses to run tests and I've added another one that makes use of `NeomakeSh`, this is all working fine but it has made me discover that there is no way, or I can't see a way, of setting a custom errorformat to commands that are executed using `NeomakeSh`. Is this something that is possible and I've just missed it? If not, is it something that could be considered for an implementation? 

Cheers,
Mark

**Comment by blueyed** [comment]
Nice, I am using vim-test myself!

I would recommend to use `neomake#Make()` directly.
While the interface there is still sub-optimal, it's better than a command.

(I've a `neomake#MakeFromDict()` locally, which allows for better control - we could certainly add something like that.)

As for `neomake#Make()`, you would define a maker:
```
let maker = {'exe': 'pytest', 'args': list_or_string, 'errorformat': …}
call neomake#Make(0, [maker])
```

There are two new methods by now, where `process_output` might be useful in your case.  It allows to skip the `errorformat` altogether, and return a list of location/quickfix entries based on the output: https://github.com/neomake/neomake/pull/1050 (the other method `get_list_entries` can be used if no external process is involved, or gets queried otherwise).
Let me know how this works for you, and if there's anything I can do to help you.

**Comment by markwoodhall** [comment]
Thanks for taking the time to reply. Using `neomake#Make` and generating a maker on the fly using the test command generated by vim-test works perfectly for me.

**Comment by azmeuk** [comment]
@blueyed This is unrelated to this bug but, can you provide your actual pytest conf?

**Comment by blueyed** [comment]
@azmeuk 
It is based on https://github.com/radenling/vim-dispatch-neovim/pull/11 (and vim-test).
Then https://github.com/5long/pytest-vim-compiler (but I have a lot of local changes from the last time I've hacked on it / fixed it).

Then these settings:
```
let test#python#runner = 'pytest'
let test#python#pytest#executable = 'env CI=true py.test'
let g:dispatch_compilers = {'env CI=true': ''}
let test#strategy = 'dispatch'
" let test#python#pytest#options = "--tb=auto -q"
" XXX: specified in compiler, get/use it from there!?!
" https://github.com/janko-m/vim-test/issues/145
" --color=no because of the '|tee' with dispatch-neovim?!
" let test#python#pytest#options = "--color=no --tb=short -q"
let test#python#pytest#options = "--color=no -p no:sugar --tb=short -q"
" let test#python#pytest#executable = "py.test"

let g:test#runner_commands = ['PyTest']
```

That is missing something probably..

Currently I am more relying on https://github.com/kopischke/vim-fetch to easily get to some file, and have pytest running in its own terminal.

**Comment by azmeuk** [comment]
Thank you! It works for me. I lacked the `test#python#pytest#options` line.
