### ISSUE TITLE
Only open location/quickfix list if there are errors to report

### ISSUE THREAD

**Issue by maurizi** [neomake/neomake#122]
It's nice to see a list of errors below the buffer (especially when there aren't very many), but it's really annoying to have an empty menu open up, especially if you are running Neomake on save.

**Comment by benekastah** [comment]
Hm, I thought we were using `cwindow` and `lwindow` for this, which should only open if there are errors. If we aren't, this will be an easy fix.

**Comment by benekastah** [comment]
So we are using `cwindow` and `lwindow` already. Those should only open the list window if there are recognized errors. Can you provide steps on how to reproduce this?

**Comment by gibiansky** [comment]
Why does the `lwindow` window close as soon as the cursor leaves it?

**Comment by benekastah** [comment]
I'm not sure why that would happen. Can you describe the full behavior? Also I'd like to know what neomake settings you're using if any.

**Comment by alathon** [comment]
I don't know if this is related, but this is the behavior I get:

- With neomake_open_list = 0, an error sign is placed appropriately but the error window never shows. I think this is the intended behavior for a value of 0?
- With neomake_open_list = 1, an error sign is not placed, instead the error window opens. It forces the cursor to it, and any time I try and leave that window it goes back after about half a second; perhaps because it keeps re-running Neomake, for some reason?
- With neomake_open_list = 2, I get nothing at all. Neither the error window, or error signs.

This is with the eslint maker, editing JavaScript code.

I was trying to get the following behavior when I came across this ticket:
- When there is any sort of error in the file (regardless of whether it is where I am looking in the file atm), the error window is shown, *and* signs on the left-hand sign if I browse to the location.

**Comment by blueyed** [comment]
> Any other info I can provide to help debug this?

Try `let g:neomake_verbose = 3`.

**Comment by kuba-gaj** [comment]
I have similar issue of location list staying open after fixing all linting errors. Have you ever found a fix?

**Comment by blueyed** [comment]
@kuba-gaj 
There have been many changes in this regard.
You are better off filing a new issue, with steps to reproduce and describing what you expect.
Also try it with a minimal vimrc, since e.g. plugins like vim-qf can interfere here.

**Comment by blueyed** [comment]
@kuba-gaj 
Actually I could reproduce it already.  Will try to fix it soon.

**Comment by kuba-gaj** [comment]
@blueyed 
Thank you for that changes but unfortunately they did not help in my case. 
What information would you like me to provide that would help in finding a cause?
Looking here looks like the changes were not merged in the end, is that correct?

**Comment by blueyed** [comment]
@kuba-gaj 
They were merged in https://github.com/neomake/neomake/commit/604ddb5d6e7c259583c1c8c5850e67a7d7a25f9a.

I need steps to reproduce it: the best would be to create a new issue and follow the issue template.

I've just tried it using a minimal vimrc (from Neomake's plugin dir, using the vint maker):

```vim
set runtimepath+=$PWD
let g:neomake_logfile = '/tmp/neomake.log'
let g:neomake_open_list = 2
```

`nvim -u minimal.vimrc t.vim`

The list was opened in case of errors, and closed after fixing them - running `Neomake vint` manually.
