### ISSUE TITLE
Highlighting makes source code unreadable 

### ISSUE THREAD

**Issue by kdubovikov** [neomake/neomake#1463]
<img width="860" alt="screen shot 2017-07-18 at 00 57 13" src="https://user-images.githubusercontent.com/832185/28291718-500930d2-6b54-11e7-9efc-bd123dcd04d1.png">

I am using Zenburn color scheme and Neomake highlighting makes text color very close to background.  I've read `:help neomake-highlight` and created this configuration:
```
augroup my_neomake_signs
        au!
        autocmd ColorScheme *
            \ hi NeomakeErrorSign ctermfg=red |
            \ hi NeomakeWarningSign ctermfg=yellow |
            \ hi NeomakeInfoSign ctermfg=white |
            \ hi NeomakeMessageSign ctermfg=white
    augroup END
```

Hoverer, I did not managed to change Neomake's default colors to fix the issue. How can I change text color when neomake highlights errors?

#### Neomake debug information
Async support: 1
Current filetype: 
Windows: 0
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]

##### Enabled makers
For the current filetype ("", used with :Neomake): None.
NOTE: the current buffer does not have a filetype.

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_place_signs = 1
```

#### :version
```

NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Скомпилирован  brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

            общесистемный файл vimrc: "$VIM/sysinit.vim"
          значение $VIM по умолчанию: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"

```

#### :messages
```

```

**Comment by blueyed** [comment]
> I've read :help neomake-highlight

Great.. :)
It does not talk about `*Sign` groups there though, but 
 - NeomakeError
 - NeomakeWarning
 - NeomakeInfo
 - NeomakeMessage

Let me know if that helps.
I am interested in good defaults, so will look into how this can be improved.

**Comment by kernelmode** [comment]
It works perfectly in good old vim though. I've currently do not have neovim installed, so I will try to check that again later.

**Comment by allan-simon** [comment]
I'm facing the same problem right now (i.e warning making the highlighted code to have same color as the background) with colorscheme "default"  and "torte" but it became readable with colorscheme "darkblue"

**Comment by blueyed** [comment]
@allan-simon 
Vim or Neovim?  Which version / OS / terminal?

**Comment by allan-simon** [comment]
neovim 0.2.0 on ubuntu 16.04 ith a xterm compatible terminal  (lxterminal from lxde )

**Comment by Mac21** [comment]
I have been poking around with this for a while and I believe I have found the issue.

1. It seems this [code](https://github.com/neomake/neomake/blob/master/autoload/neomake/highlights.vim#L122) is using the bg attribute of the Error highlight instead of the fg attribute.

2. If that is the intended attribute could a case be added that checks to see if the Normal highlight bg is equal to the value we compute? This would mean that the text is going to be invisible. So we could call the ReverSynIdAttr and retrieve the value again.

**Comment by blueyed** [comment]
How does `:hi Error` look for you?

I have

> Error          xxx cterm=reverse ctermfg=1 guifg=White guibg=Red

The default theme in nvim has:

> Error          xxx ctermfg=15 ctermbg=9 guifg=White guibg=Red

IIRC the reverse in my case gets handled, so it should end up being red in both cases.

**Comment by Mac21** [comment]
I am using space-vim-dark colorscheme and NVIM 0.1.7

Neomake auto runs due to `autocmd! BufWritePost * Neomake`.

:hi Error
`Error xxx cterm=bold ctermfg=160 ctermbg=235 gui=bold guifg=#e0211d guibg=#292b2e`

I started poking around because I wasn't able to over ride the default NeomakeError with the following:

```
augroup my_neomake_highlights
        au!
        autocmd ColorScheme *
            \ hi link NeomakeError SpellBad |
            \ hi link NeomakeWarning SpellCap
augroup END
```

Although that may be an unrelated issue.

If a colorscheme doesn't have reverse attribute on the Error highlight group would it be possible to compare the bg attribute value of the Normal highlight group against the value that GetHighlight returns?

**Comment by blueyed** [comment]
https://github.com/neomake/neomake/pull/1827 should fix it.

@Mac21 
I've tested again if the example works, and it kicks in after using `:colorscheme default`.
Do I miss something, or have you put this after your call to `colorscheme`?
