### ISSUE TITLE
c++ clang-tidy no longer uses local compile_commands.json

### ISSUE THREAD

**Issue by jasonwzz** [neomake/neomake#1596]
Hi @mqudsi , as requested, opening a separate issue. 

This is a simple example that is going to trigger the issue:
In `test.cpp` : 
```
int main(){
#ifdef DEFINE_A
  int a = 1;
#endif
  return a;
}
```
In `compile_commands.json` (both are in the same directory):
```
[
  {
    "arguments": [
      "c++",
      "-DDEFINE_A",
      "test.cpp"
    ],
    "directory": "/path/to/your/directory" ,
    "file": "test.cpp"
  }
]
```
Expectation:
When running `:Neomake`, clang-tidy will pick the arguments defined in `compile_commands.json` and define macro `DEFINE_A`. No error will be reported.

Actual behavior:
Error is reported:
"clangtidy: use of undeclared identifier 'a' [clang-diagnostic-error] (E)"

Also the above was working before I updated Neomake to the latest version.

A bit of investigation suggests that this is because the new `--` passed after `clang-tidy`.

For example, in the same directory, if you do:
```
clang-tidy test.cpp
```
then no error is reported.

If you do:
```
clang-tidy test.cpp -- -std=c++1z
```
An error will be reported.

It seems clang tooling will pick either the compilation options specified after "--" or the ones specified in the compilation database. If you have both, then only the options after "--" will be used.

However, I haven't been able to find any official documentation about this behavior. Maybe it's buried somewhere the documentation pages or in the code... So not sure if it's by design or just happened to be like this.

Thanks.

**Comment by blueyed** [comment]
Would `clang-tidy -- test.cpp -std=c++1z` work?

**Comment by jasonwzz** [comment]
@blueyed nope..  Error: no input files specified.
`clang-tidy test.cpp -- test.cpp -std=c++1z`
doesn't work either. still giving the same 
use of undeclared identifier 'a' [clang-diagnostic-error].

**Comment by Bergiu** [comment]
I have the same error. When I type :Neomake I encounter one of these three errors:
```clangtidy: 'csv.h' file not found [clang-diagnostic-error] (E)
clangcheck: fatal error: 'csv.h' file not found (W)
clang: fatal error: 'csv.h' file not found (W)```

I think this problem is depending on the order of the compile parameters. If i change the line 

in
https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/cpp.vim

**Comment by blueyed** [comment]
Instead of `--` `-extra-arg` could be used maybe?
`clang-tidy test.cpp -extra-arg '-std=c++1z'` works with the example.
To reflect current options `clang-tidy test.cpp -extra-arg '-std=c++1z' -extra-arg '-I./'` should be used then.

But why use `'-std=c++1z'` in the first place?
I think this should be configured by the project itself, no? (via .clang-tidy)

Also the `-I./` does not need to be necessary: `#include "meh.h"` is handled properly (opened from the cwd of the .cpp file itself).
`LLVM version 6.0.0`

Changes are from 8794ee65 / /cc @mqudsi.

I suggest removing the custom config `-- *`.

**Comment by Bergiu** [comment]
`<>` should be rigth

**Comment by blueyed** [comment]
> `<meh.h>` should be right.

Then the `-I` should be kept.
However, using `-I./` fails when not in the same dir already - for this the cwd should be changed, or the full (relative) path to the current file be used.
Doesn't it make sense to have this in the config then, too? `compile_commands.json` will include it already.

**Comment by Bergiu** [comment]
`compile_commands.json` includes the `-I` already, but it is not passed to the clang (and maybe gcc) maker.args.

**Comment by Bergiu** [comment]
But I still get the error `clang: fatal error: 'fast-cpp-csv-parser/csv.h' file not found (W)`.
Should I open a new issue for this?

I can remove the issue by removing 'clang' from line 4 in https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/cpp.vim, but that removes a feature and not the bug.

**Comment by blueyed** [comment]
Found the Python API btw:
```python
import os

from clang import cindex

path = '/home/daniel/src/awesome/build/awesome.c'
d = os.path.dirname(path)
compdb = cindex.CompilationDatabase.fromDirectory(d)
compile_commands = compdb.getCompileCommands(path)
if compile_commands:
    print(list(compile_commands[0].arguments))
```

But in the case of awesomeWM that shows a problem already: source files are put into a separate directory using `configure_file` in CMake, and therefore the source location would have to be mapped already for the lookup in the compilation database.

I've also looked at https://github.com/prabirshrestha/vim-lsp briefly, which uses clangd via the LSP, and for more complex projects it's probably recommended / a good idea to go the LSP route.

**Comment by mqudsi** [comment]
Sorry for the delayed response, it's been an insane week for me. The manually added parameters were to enable neomake to be used with one-off code that isn't part of a (cmake) project. For example, editing a single cpp file or a basic utility where a compilation commands database wouldn't exist, or writing a c/cpp file from scratch. The explicit `--std=c++1z` was to default to all C++ features unlocked, without it even C++11 features (with some of the versions of clang/gcc still in use in many LTS distros) will be disabled, rendering neomake useless in that case.

**Comment by blueyed** [comment]
@mqudsi 
No worries.
So you would suggest adding `-extra-arg '-std=c++1z' -extra-arg '-I$DIR_OF_FILE'` then I assume?

**Comment by mqudsi** [comment]
@blueyed That would be my inclination, yes. But we are discussing two separate issues here, I think (the default arguments and the compilation commands).

Regarding the latter, note that the cmake wiki also mentions this tidbit which I didn't know about:

> For simple projects, Clang tools also recognize a compile_flags.txt file. This should contain one flag per line. The same flags will be used to compile any file.

I'm trying to see if you actually ever need to re-invoke clang yourself, though. Is neomake supposed to supplant the build system or just provide error detection and linting? Because the situation has drastically improved over the past few clang versions, and now all (?) clang tools support reading the compilation database and extracting the relevant info from there themselves - I don't think you need to parse it.

Also note from the `clang-check` man page:

> -p <build-path> is used to read a compile command database.
> 
> For example, it can be a CMake build directory in which a file named compile_commands.json exists (use -DCMAKE_EXPORT_COM‐ PILE_COMMANDS=ON  CMake option  to  get this output). **When no build path is specified, a search for compile_commands.json will be attempted through all parent paths of the first input file.** See: http://clang.llvm.org/docs/HowToSetupToolingFor‐ LLVM.html for an example of setting up Clang Tooling on a source tree.

Which should take care of a lot of the cases. The only issue here is that cmake builds are traditionally out-of-root, often in a top-level directory named 'build' (in the project root), which is where the compilation_commands.json file would end up (and isn't automatically searched by `-p`).
