### ISSUE TITLE
Formatting with Neomake (using automake functionality)

### ISSUE THREAD

**Issue by lwm** [neomake/neomake#1784]
Ahoy! I just found https://github.com/google/yapf and thought about the automake functionality here and wanted to see if I couldn't rig it up to automatically format my code as I write. I had:

```
let g:neomake_python_yapf_maker = {'exe': 'yapf'}
let g:neomake_python_enabled_makers=['pylama', 'vulture', 'yapf']
```

And then was seeing that it was working in debug output with:

```
19:04:59 [D      ] [1.3:1:1] stdout: yapf: ['foobar = (1, 2, 3, 5, 6, 7)', ''].
19:04:59 [D      ] [1.3:1:1] exit: yapf: 0.  
```

I then realised that the output is typically used for showing in the quickfix list and not for updating the file I'm working on. So, I started to think that I'm doing it wrong or NeoMake shouldn't be used for this. Thoughts?

PS. I saw neoformat exists but then [this](https://github.com/sbdchd/neoformat/issues/106).

**Comment by blueyed** [comment]
Neomake is not really suited for this as of now, but mainly only since there is no way to skip location/quickfix list processing (and messing with existing ones) (but it should not be hard to add).

As for your maker, you want to use `let g:neomake_python_yapf_maker = {'exe': 'yapf', 'args': ['--in-place']}` probably.

Anoher issue then is automatically reloading the buffer.  I am seeing W11 myself, which I have to confirm (this depends on your Vim settings).

Given that you cannot change the buffer anyway during the fixing, and likely not want to do it really too often, you could just use a command: `command! -range=% -nargs=* Yapf exe '!yapf --in-place --lines <line1>-<line2> <args>'.expand('%')`

Can also be adopted to view the diff only.
Of course, doing this on `BufWritePost` synchronously is possible, too.

Apart from that, it is probably better to use neoformat for better integration altogether, given that it can be used async again.

Closing this issue here for now, but thanks for showing this possible use case.
Refactoring file/project mode (location/quickfix list handling) is something I want to do anyway.

**Comment by lwm** [comment]
Awesome, thanks! :)

**Comment by blueyed** [comment]
Related: https://github.com/neomake/neomake/issues/1037.

**Comment by xiumingzhang** [comment]
Hi, @blueyed. I wonder if we have solutions to automatically reloading the buffer after
```vim
let g:neomake_python_yapf_maker = {'exe': 'yapf', 'args': ['--in-place']}
```
makes some changes? Thanks.
