### ISSUE TITLE
Request: flog for ruby files

### ISSUE THREAD

**Issue by firedev** [neomake/neomake#192]
Hi,

Is it possible to add `flog` suport?

https://github.com/scrooloose/syntastic/wiki/Ruby:---flog

Thanks.

**Comment by benekastah** [comment]
Adding new makers is generally pretty simple. Due to my own time constraints, I tend to depend on the community to add makers I don't personally use. This also helps ensure that the maker works for a real user. Feel free to check out the [current ruby makers](https://github.com/benekastah/neomake/blob/master/autoload/neomake/makers/ft/ruby.vim). Using those as examples (and by perusing the neomake docs), I imagine it won't be too difficult to get it working.

**Comment by blueyed** [comment]
@firedev 
Have you looked into creating a maker for it?
