### ISSUE TITLE
No messages on checker success

### ISSUE THREAD

**Issue by rhelmot** [neomake/neomake#1938]
I updated neomake recently. Previously, when I ran neomake I would see `pylint exited with status 0` or similar on success. Now, I don't see anything like that. I like this message because otherwise I don't know if the checker is just taking a very long time. pylint on a large project can take >10 seconds; this was a big motivation for me to switch to neomake so this could be run async.

From playing with the verbosity levels and looking at the log files, it seems like this is now a debug message? How can I make it appear without enabling debug output?

**Comment by rhelmot** [comment]
The bot has conveniently helped me discover that the best way to solve this problem is actually with a statusline, but I'm not a very good vim scripter and I do think the success message should be visible by default.

**Comment by blueyed** [comment]
The statusline is the way to go indeed.  Are you using something like vim-airline already, or do you have a custom or default statusline?

You could try `:set stl=%!neomake#statusline#get(bufnr('%'),\ {})` for demo purposes - it will replace your whole statusline, and is not correct in general, since it uses the current bufnr, and statuslines should not do that (for non-current windows).  Check `:h 'statusline'` for details.
Setting up your statusline can be a time sink, so be cautious.. ;)

It was changed back in 37ced7db (in 2016) to fix https://github.com/neomake/neomake/issues/238.

**Comment by blueyed** [comment]
You could also define a user autocommand:

```vim
autocmd User NeomakeJobFinished echom printf('%s exited with %d', g:neomake_hook_context.jobinfo.maker.name, g:neomake_hook_context.jobinfo.exit_code)
```

**Comment by rhelmot** [comment]
Maybe I'm missing something really huge, but I can't get the statusline stuff to work. The main thing is that neomake#status#get() seems to really want to be used from within a `%{}` context, but it returns `%#Highlights#` which don't actually seem to render when used in said context. I'm getting statuslines of `%#NeomakeStatColorTypeE# E:6 %#NeomakeStatColorTypeW# W:1`.

**Comment by rhelmot** [comment]
Figured it out, finally.

```
function! MyStatusNeomake(buf)
    return neomake#statusline#get(a:buf, {
          \ 'format_running': '… ({{running_job_names}})',
          \ 'format_loclist_ok': '✓',
          \ 'format_quickfix_ok': '',
          \ 'format_quickfix_issues': '%s',
          \ })
endfunction

" This function, given a buffer number, returns the current statusline for it.
" it will be called very often.
function! StatusLine(buf)
    return "%f\ %h%w%m%r\ " . MyStatusNeomake(a:buf) . "%*%=%(%l,%c%V\ %=\ %P%)"
endfunction

" This function is set as the initial statusline, but quickly commits suicide
" by setting a local statusline that will always be called with the correct
" buffer number.
function! SetStatusLine()
    echo 'called'
    let &l:statusline = '%!StatusLine(' . bufnr('%') . ')'
endfunction

" This installs the above setter.
set statusline=%!SetStatusLine()
```

Is there perhaps an easier way to do this?

**Comment by blueyed** [comment]
You could use `g:actual_curbuf`.
Only found out about this myself.
Working on improving the interface in https://github.com/neomake/neomake/pull/1941.

I've thought about a `neomake#statusline#get_for_expr` wrapper, but this does not allow for options passed in via a dict directly because of https://github.com/vim/vim/issues/2829.
