### ISSUE TITLE
How to remove "||" in quickfix windows

### ISSUE THREAD

**Issue by tracyone** [neomake/neomake#1963]
or change other charactor?

**Comment by blueyed** [comment]
@tracyone 
This is an indicator for "invalid" entries, i.e. those not matching the `errorformat`.
Which maker are you using, and how does the output look?

**Comment by tracyone** [comment]
![_020](https://user-images.githubusercontent.com/4246425/40274277-3dc37f84-5c05-11e8-9ea2-8a6d24a83df3.png)

provide an option to remove the selected charactor: "||",   only show the content

**Comment by blueyed** [comment]
This is due to "invalid"/unrecognized entries in the location list.
There is an option to remove those per maker etc (`remove_invalid_entries`), but usually the errorformat should remove/handle them already.
It is a Vim feature itself, the character(s) cannot be changed.

But Neomake has some custom quickfix handling already (after `:call neomake#quickfix#enable()`), where this could be done maybe.
