### ISSUE TITLE
out of tree builds and errorformat parsing

### ISSUE THREAD

**Issue by teto** [neomake/neomake#2026]
### Expected behavior

I am trying to get a good enough maker for nixos, but I have a problem depending on if packages follow out of tree or in-tree builds. If the maker has the wrong "cwd" than the errorformat rules fail and I can't jump from quickfix entries to the code.  Basically I would neomake to detect if there is a "build" folder and if there is adjust the maker's cwd accordingly. 

 aka I
1. run a `nix-shell -A mypkg <nixos>`
2. start neovim
3. Run  `BuildPhase`

### Steps to reproduce

Here is my workaround, I wonder if there is something better ? 

```
let g:neomake_buildPhase_maker = {
    \ 'exe': '/home/teto/dotfiles/bin/nix-shell-maker.sh',
    \ 'args': [],
    \ 'errorformat': '%f:%l:%c: %m',
    \ 'remove_invalid_entries': 0,
    \ 'buffer_output': 0
    \ }

function! RunBuildPhase()

  if isdirectory("build")
    let g:neomake_buildPhase_maker.cwd = getcwd().'/build'
  else 
    unlet g:neomake_buildPhase_maker.cwd
  endif
  Neomake! buildPhase

endfunc 

command! BuildPhase call RunBuildPhase()

```

**Comment by blueyed** [comment]
Has `nix-shell -A mypkg <nixos>` any output that indicates where it goes to?
See `%D` and `%X` in `:help error-file-format` (http://vimdoc.sourceforge.net/htmldoc/quickfix.html#error-file-format).

**Comment by blueyed** [comment]
Apart from that, check usage of `neomake#utils#FindGlobFile` in other makers.  I assume it works for dirs also, but could be enhanced otherwise.
`%D` would be better though I assume.
Not sure if Neomake really handles it well though, since it `cd`s itself (job start and when parsing the output into lists)..

**Comment by blueyed** [comment]
You can also set `cwd` dynamically in the maker (no need to wrap it in a function).

Should work in the `fn` callback, and elsewhere likely.  Search for `cwd` in existing makers.

**Comment by blueyed** [comment]
I've just wondered, because `make` for example has lines like "Entering directory", and "Leaving directory" that can be parsed from &errorformat.
(but currently output from its stdout/stderr is not merged, which breaks this - https://github.com/neomake/neomake/issues/1884; I've started working on a fix in https://github.com/neomake/neomake/pull/2054 (which is missing the actual merging still though)).

There is no help for `maker.fn` intentionally, since it should be cleaned up (i.e. its name) / is considered experimental still.  It gets used when instantiating a maker (https://github.com/neomake/neomake/blob/a47a13bb94fef82d6caf57a72a88cfc8085ca854/autoload/neomake/core.vim#L12-L21).
You can set `self.cwd` therein - tests are probably the best way to find examples.

**Comment by teto** [comment]
This seems to work
```
function! Check_build_folder(opts, ) abort dict

  " todo check for nix-shell
  if isdirectory("build")
    let self.cwd = getcwd().'/build'
  endif

  return self
endfunction

```

The script it launches generates an error when I am not in a nix-shell but even though I have location_list set to 2, the quickfix/location list won't open. The message "you are not in a nix-shel" does appear if I do copen though.
```
15:19:15 [D      ] [4.1:26:1] Creating quickfix list.
15:19:15 [D      ] [4.1:26:1] Processing 1 entries.
15:19:15 [D      ] [4.1:26:1] Skipped 1 entries without bufnr: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'maker_name': 'buildPhase', 'pattern': '', 'text': 'you are not in a nix-shell'}].
15:19:15 [D      ] [4.1:26:1] Handling quickfix list: executing cwindow.
15:19:15 [D      ] [4.1:26:1] stdout: buildPhase: [''].
```

Here is the script started by the maker

```

#!/usr/bin/env bash
if [ -z $IN_NIX_SHELL ];
then
	echo "you are not in a nix-shell"
	exit 1
fi

```

Anyway it's much better than what I have before and I am really happy to get this working. I might contribute it once I get things ironed out.

**Comment by blueyed** [comment]
The list does not open since there are no recognized errors - it is using `cwindow`, not `copen`; therefore this part is expected.

**Comment by teto** [comment]
Closing since my initial question is answered. thanks for the help. <3
