### ISSUE TITLE
Sign column background color is getting reset

### ISSUE THREAD

**Issue by andrewbredow** [neomake/neomake#204]
I like the default behavior of GitGutter which is to keep the same background color as the line number column ([link](https://github.com/airblade/vim-gitgutter#sign-column)). It would be awsome if neomake would do the same thing for error/warning signs.

<img width="167" alt="screen shot 2015-11-01 at 10 45 07 am" src="https://cloud.githubusercontent.com/assets/96793/10869736/1ad4d6e2-8086-11e5-9df2-e3b1f19b73cb.png">

**Comment by benekastah** [comment]
I remember looking into this a while back. IIRC, gitgutter does some pretty tricky stuff to figure out the appropriate background color for their signs. If someone wants to figure out what they did and apply that into a PR here, I'm happy to merge it.

In the meantime, if this is bugging you you can configure the signs to your liking. See `:h g:neomake_error_sign`. You'll have to learn about how vim does highlighting (see `:h sign-define`).

**Comment by andrewbredow** [comment]
Yes, I looked into a little, but it wasn't immediately clear what's going on. I'll dig in a little deeper and give it another shot. It's definitely a nice feature.

**Comment by jrolfs** [comment]
@andrewbredow: So, #248 fixes this and allows easier override for the background, however it was reverted due to incompatibility issues.

Since I didn't want to maintain a fork in my dotfiles, I went ahead and implemented a solution based on the aforementioned PR in my own configuration:

[Highlight Defaults](https://gist.github.com/jrolfs/2be35593f117e3b19647009c7de7408c)
[vimrc/init.vim](https://gist.github.com/jrolfs/74de7da961d358aeea8cd8a48e1818bd)

**Comment by andrewbredow** [comment]
@jrolfs Thanks!

**Comment by jrolfs** [comment]
My pleasure, hopefully I can improve my vim/VimL skills over time and maybe help get that PR in so color themes can take advantage of the highlights!

**Comment by blueyed** [comment]
You might want to try https://github.com/neomake/neomake/pull/456.. :)
