### ISSUE TITLE
An autoconfiguration way question

### ISSUE THREAD

**Issue by Eluminae** [neomake/neomake#2183]
Hello there !

I'm trying to configure all my plugin using only variable declaration. The goal is that my vim can run without any error/warning when I do not call :PlugInstall (ex: in distant servers)

But I got a problem with Neomake ! The documentation explicitly say that I have to call "neomake#configure#automake('rw', 1000)".

My question is : can't we just declare an g:neomake="rw 1000" or something ?
The neomake plugin can't just configure itself correctly using variable ?

TY by advance !

**Comment by blueyed** [comment]
You could just define the autocommands manually.
It is meant as a convenience method to configure automaking.  Using only variables does not really work here, since it needs to setup autocommands etc.

I suggest calling it only in some condition (e.g. `if &rtp =~ '\<neomake\>'`, if you want to skip it without Neomake being installed).
