### ISSUE TITLE
duplicate tags in help

### ISSUE THREAD

**Issue by campbellr** [neomake/neomake#283]
After pulling the latest code (e0fa23401c1231bd942779c79c5c71d08f28e440), `pathogen` complains about duplicate help tags:

```
Error detected while processing function pathogen#helptags:
line    5:
E154: Duplicate tag "callback" in file /localhome/campbr9/.config/nvim/bundle/neomake/doc/neomake.txt
E154: Duplicate tag "callback" in file /localhome/campbr9/.config/nvim/bundle/neomake/doc/neomake.txt
E154: Duplicate tag "callback" in file /localhome/campbr9/.config/nvim/bundle/neomake/doc/neomake.txt
E154: Duplicate tag "callback" in file /localhome/campbr9/.config/nvim/bundle/neomake/doc/neomake.txt
E154: Duplicate tag "callback])" in file /localhome/campbr9/.config/nvim/bundle/neomake/doc/neomake.txt
Press ENTER or type command to continue
```

It looks like in a lot of places, `*callback*` is used when `|callback|` is intended, and `*callback*` is defined inside two function signatures.

**Comment by dnebauer** [comment]
Duplicate tag 'NeomakeCountsChanged' added in commit [f417f27](https://github.com/neomake/neomake/commit/f417f27d1a4684ece30aa5bbc32038229f01707a). This is because \*NeomakeCountsChanged\* is used instead of |NeomakeCountsChanged| in line 399 (line 405 at time of this comment).

Duplicate tag 'NeomakeFinished' added in commit [10fb27f](https://github.com/neomake/neomake/commit/10fb27fe01365e3c26e3fbd4fac22a2ac41d8788).This is because \*NeomakeFinished\* is used instead of |NeomakeFinished| in line 392 (line 398 at time of this comment).

**Comment by blueyed** [comment]
Thanks for the report - I was not aware of it until the PR.
