### ISSUE TITLE
How to use cargo maker?

### ISSUE THREAD

**Issue by TyOverby** [neomake/neomake#318]
I have the `rustc` maker working, but I have no idea how to get cargo to run on every save.

**Comment by sbdchd** [comment]
You can run the `cargo` maker with `:Neomake! cargo`.

**Comment by michael-younkin** [comment]
To clarify, `neomake` has a preconfigured maker for `cargo`, it just doesn't run it automatically. To set this up, you have to write your own `autocmd` (which basically is an event handler in vim). Here's mine:

```viml
" Neomake configuration.
augroup my_neomake_cmds
	autocmd!
	" Have neomake run cargo when Rust files are saved.
	autocmd BufWritePost *.rs Neomake! cargo
augroup END
```

Note the use of `Neomake!`, which (I think) calls `cargo` without passing it a file name, which is necessary for Rust because you need to read the entire crate to do type checking stuff.

**Comment by rivertam** [comment]
I'm getting "cargo is not an executable" but it is. Any ideas?

**Comment by blueyed** [comment]
@rivertam 
Does `:!cargo --help` work?
Please create a new issue if the problem still exists, and provide more information, e.g. if you are using Vim, Windows etc.
