### ISSUE TITLE
Add "serialized" support per maker / ft

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#577]
Given makers A, B, C it would be nice to specify only some makers as serialized, e.g. if "A" fails there is no need to run B and C.

But if B fails, C should still run.

With Python that would be python, flake8 and pydocstyle: python reports syntax errors only, which willl be reported again from the other makers then, too - and not much more in general.

**Comment by davidosomething** [comment]
I don't think i'd ever use this since it basically goes back to synchronous linting.

The linters run as separately so you'd still be checking over the same errors and getting the same output.

How about just a "cancel jobs" flag that stops processing of all makers instead? It's weird to tie individual linters together (that's more of a job for the wrapper linters like flake8, which runs pyflakes and pep8)

e.g. `let g:neomake_python_python_maker = {
  'exe': 'python',
  ...
  'abort': true,
}`

so if python has errors, abort all other neomake jobs.

**Comment by blueyed** [comment]
@davidosomething 
I think the new `{ 'abort': true }` is what `{ 'serialize': 1, 'serialize_abort_on_error': 1 }` is meant to do (i.e. another name / shortcut)?

**Comment by davidosomething** [comment]
when you run with `'serialize': 1`, does it start A, B, and C at the same time and just serialize the output, or does it actually run serially (A, check status, B, check status, C)?

**Comment by blueyed** [comment]
It runs after each other: the code in this regard is a bit broken though, but I came across it a while ago (probably when I've created this issue here).

**Comment by davidosomething** [comment]
Then there is a difference between abort on parallel jobs and serialize_abort_on_error:

if A takes 10 seconds and B takes 1 second, and b is an `abort: 1`

- If serialize_abort_on_error will abort after B fails (11 seconds)
- whereas `abort: 1` on a parallel job will abort after 1 second (only B completes, A cancelled 9 seconds early because B exited with error and was flagged abort)

**Comment by blueyed** [comment]
I see, and think it might be useful additionally.

For the python makers however, it should really (have a mode to) start the other makers (in parallel) only after python was successful: it is fast and only reports syntax errors.
