### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#826]
@mhinz came up with https://logomakr.com/5CsPeq already.

This should be used for the GitHub organization.

**Comment by wsdjeg** [comment]
@blueyed, nice, how about change the bg to green?

**Comment by mhinz** [comment]
I added a few: https://logomakr.com/2Jtvkx

**Comment by tweekmonster** [comment]
The idea of Neomake is a little too abstract.  I went with the build badge as the inspiration since, you know, linting helps reduce mistakes.  But, I kind of like the no-background version.  They're pretty plain, but clean:

![neomake](https://cloud.githubusercontent.com/assets/111942/21515490/4544d548-cc9e-11e6-8da4-41a1d756f46e.png)

You all seemed to like the idea of using a shield, so I gave it a proper design:

![neomake-shield](https://cloud.githubusercontent.com/assets/111942/21515538/c22b3a2a-cc9e-11e6-97aa-a3e35f92fcc9.png)

But my creative juices started went into Turbo.  I had to give the Neomake name the full Hollywood treatment:

![neomake-serious](https://cloud.githubusercontent.com/assets/111942/21515554/ec7d7536-cc9e-11e6-925c-0c4bf7c449bf.png)

With this one, people will think the project was funded by a major movie studio.

**Comment by mhinz** [comment]
Okay, those are all awesome. The shield one might be a bit too much, though. :-D

First I thought it's just funny, but I happen to like the last one! The first ones all look good and clean, but the last one is certainly different to most other logos. Could you make an icon version of it in the same style? Purple background, big yellow N?

**Comment by blueyed** [comment]
I like the first one (and the 2nd variant there more).

What about 2. with a "Neomake" below the "N"?

**Comment by tweekmonster** [comment]
Here's the 80's style logo with better graphic treatments:

![neomake-the-movie](https://cloud.githubusercontent.com/assets/111942/21532716/e01ac21c-cd20-11e6-813e-3a6089f8017f.png)

![neomake-the-movie-sticker](https://cloud.githubusercontent.com/assets/111942/21532718/e4cd6940-cd20-11e6-902b-c0918349f801.png)

![neomake-the-movie-sticker-100](https://cloud.githubusercontent.com/assets/111942/21532735/0870f77c-cd21-11e6-93eb-142c2d6912ef.png)

![neomake-the-movie-sticker-48](https://cloud.githubusercontent.com/assets/111942/21532737/0d09e794-cd21-11e6-9679-041f30b3954c.png)

ASCII version that needs tweaking:

```
                                                                
                                                    :***%*;,    
                   ,,,;,        ,;;-             ,&;::::*'`     
                  ;;;;;;~      ;;;;;'          :%;;;;*'         
                 ;;;;;;;;     ,;;;;'          &;;;;*            
                ;;;;;*;;;%    *;;;* :%!;%&  :!;;;*`             
               %;;;; ';;;;;  %;;;*  !;;;;~ ;;;;;%               
              %;;;*   '!;;;;%;;;*   !;;;;~;;;;;"                
             &!!!%     '!!!!!!!*    !!!!!!!!!!"                 
            &!!!%       !!!!!!*      %!!!!!!!%                  
           %%%%%         %%%%%~      '%%%%%%%                   
          !&&&&         ;&&&&"         %%&%"                    
             '"          ` ^"                                   
                                                                
```

If you try really hard to love it and squint your eyes, it looks like the `N` and the `✓` combine to form the letter `M`.  It also has the whole "new" radical feel to it.  The only thing it's missing are streaks of lightning with electric blue to give it that futuristic feeling.

@blueyed Do you mean something like this?

![neomake2](https://cloud.githubusercontent.com/assets/111942/21533041/bae8c65c-cd24-11e6-821a-021387562d36.png)

In any case, I'm not a fan of repeating letters or words.

**Comment by mhinz** [comment]
If Neomake doesn't take it, we take the 80ies logo for vimmer.net. :-)

**Comment by tweekmonster** [comment]
![vimmer net](https://cloud.githubusercontent.com/assets/111942/21533778/32dde1cc-cd2c-11e6-83fb-e2162634ce17.png)

I can already hear the fast paced synth keyboard.

**Comment by blueyed** [comment]
@tweekmonster 
I've imagined to have the word below the N, but in the box.

**Comment by tweekmonster** [comment]
@blueyed Like this?

![neomake3](https://cloud.githubusercontent.com/assets/111942/21572296/6c72f77c-cea5-11e6-8d1f-84fdf3a734cc.png)

I have to say that I don't like it.  The `N` is redundant without additional meaning.  It's just stuttering.  Some examples why this isn't good style:

![superman s_classic_pose](https://cloud.githubusercontent.com/assets/111942/21572303/814fe876-cea5-11e6-95a8-fb83a8b98fd6.jpg)

![oonce-upon](https://cloud.githubusercontent.com/assets/111942/21572307/85e2f996-cea5-11e6-8fd5-57e8a55b9534.jpg)

**Comment by blueyed** [comment]
I see.
Then it should be seen as a variant of 5: using only the left half of it and the checkmark instead of the "N".

**Comment by tweekmonster** [comment]
@blueyed I'm not sure if I understand.  Could you mock up what you're describing?  It doesn't have to look nice.

Also, I should've clarified with the images I posted.  `1` is meant as a banner type image for the README.md while the others are choices for the org profile picture.

The banner is mainly so the README isn't boring.  It's wide because there's no real control over layout.  The reason I like the one with no background is because it sometimes looks weird if there's a hard boundary created by an image.

The profile picture doesn't need to have the full name in it since the name is already part of the profile page, and it wouldn't be very legible at 100x100 and 38x38 anyways.

I should've done this earlier, but here's mockups of the README:

## No background

![](https://share.esdf.io/sDAJ4NhJKZ/Screen-Shot-2016-12-30-21-44-59.png)


## Background

This one looks a little weird with the build badge now that I see it.

![](https://share.esdf.io/q0ZjqmCWpY/Screen-Shot-2016-12-30-21-46-06.png)

## No background, made to look like title text

This one looks very clean and doesn't distract from the rest of the README.  I could remove the space below the image so that the line below is a little closer.

![](https://share.esdf.io/EYXxWI6wzV/Screen-Shot-2016-12-30-21-47-14.png)


# Square images

I only picked the full sqare one since it's mostly iconic.

## Profile

![](https://share.esdf.io/NwinXaH7Ll/Screen-Shot-2016-12-30-23-41-35.png)

## Organization

This is why "Neomake" shouldn't be in the image.  It would get very repetitive here.

![](https://share.esdf.io/gMMvD1lPnX/Screen-Shot-2016-12-30-23-44-39.png)

**Comment by mhinz** [comment]
I like the "no background" one, no matter the size. It's clean and elegant and fits into the README. But then the green/gray icon isn't fitting. I believe I'd prefer just the marker from the title image instead.

**Comment by wsdjeg** [comment]
also like the no backgroud one, but how could it looks like when in profiles?

**Comment by blueyed** [comment]
@tweekmonster 
LOL for my improved profile picture.. :)

Can you send it to me in high resolution, please?

I've meant something like the following for the square/org logo:

```
     //
    //
\\_//
 \_/
Neomake
```

👍 for the "no background" banner.

Another idea for the square/org logo one: can we overlay the "N" and the checkmark in some way - leading to some "M" when squinting (as described earlier)?!

**Comment by tweekmonster** [comment]
> Can you send it to me in high resolution, please?

👻

![blueyed](https://cloud.githubusercontent.com/assets/111942/21580341/297cd90c-cfbc-11e6-856e-400addd90b39.jpg)

The original if you're curious: https://share.esdf.io/XsT09RlCeg/

> I've meant something like the following for the square/org logo:

Ah, so like this? 

![neomake](https://cloud.githubusercontent.com/assets/111942/21580351/babbc23e-cfbc-11e6-9c7a-f55a79c2bf24.png)

If so, I'll need to tweak the text a little bit so the thickness is more uniform.

**Comment by mhinz** [comment]
? :>

**Comment by tweekmonster** [comment]
Lost track!  I'll try to make a version of the `N✔` that kind of looks like an `M`.  In case it turns out bad, does the last image posted above look alright @blueyed and @mhinz?  And we all like the smaller version for the readme right?

**Comment by mhinz** [comment]
Any logo is better than the current. ;-)

**Comment by tweekmonster** [comment]
I have a reputation to protect in my nonexistent graphic design career, pal.

**Comment by tweekmonster** [comment]
![neomake1](https://cloud.githubusercontent.com/assets/111942/21837263/b47caf4e-d798-11e6-989c-393699da9637.png)

![neomake2](https://cloud.githubusercontent.com/assets/111942/21837265/b8dea75e-d798-11e6-8cfa-bebf09637cf9.png)

**Comment by blueyed** [comment]
@tweekmonster 
LVGTM

Do you want to create a PR to update it?

**Comment by blueyed** [comment]
@tweekmonster 
The logo does not work so well with a dark GitHub theme, i.e. on a dark background.
GitHub's own logo seems to get inverted, probably by using opacity?!
I am using Stylish on Firefox with this theme: https://userstyles.org/styles/37035/github-dark.

![2017-02-08-001842_608x379_scrot](https://cloud.githubusercontent.com/assets/9766/22716054/3732d510-ed94-11e6-8d0f-bc0314012aad.png)

**Comment by tweekmonster** [comment]
GitHub's logo inverts because it's actually a font glyph and the stylesheet changes it.  I set the font color to red as a test:

![screen-shot-2017-02-07-18-23-54](https://cloud.githubusercontent.com/assets/111942/22716193/b76a3642-ed62-11e6-9eb2-3955a9a9dce8.png)

I can try changing the text to a shade of gray.  That might make it visible in both light/dark backgrounds.  If that doesn't work, a white stroke around the text might work.

**Comment by tweekmonster** [comment]
@blueyed How does this look with the dark background?

![neomake-logo](https://cloud.githubusercontent.com/assets/111942/22717189/9e3e1760-ed67-11e6-94c5-e8955869d6d0.png)

**Comment by blueyed** [comment]
@tweekmonster 
Much better.

**Comment by blueyed** [comment]
Applies to the org's logo, too:
![2017-02-08-225920_356x154_scrot](https://cloud.githubusercontent.com/assets/9766/22759321/4cf284e0-ee52-11e6-8b6d-4406df4f8022.png)

**Comment by tweekmonster** [comment]
Try this:

![neomake-logo](https://cloud.githubusercontent.com/assets/111942/22769852/8f77aa78-ee59-11e6-8233-2229cb9b972a.png)
