### ISSUE TITLE
How can I change bg color ouf output ? 

### ISSUE THREAD

**Issue by keyolk** [neomake/neomake#830]
Sorry if it is duplicated.
I didnt find it : (

when I get output from neomake
it puts error message like below

![screenshot from 2016-12-11 03-51-37](https://cloud.githubusercontent.com/assets/5329850/21079918/9a76bd34-bf55-11e6-8e37-ac575906f767.png)

how can I change it ?

**Comment by blueyed** [comment]
Do you mean the yellow bg?
That's your theme I would say.. is it only the highlighted line?
IIRC there is a new highlight for quickfix/location lists, but I don't know if it's Vim/Neovim (and you don't tell anyway).

I am closing this, since it's not really an issue with Neomake, but (Neo)Vim in general.

Try if `:colorscheme default` (or some other) helps.
