### ISSUE TITLE
How to close quickfix-list and location-list automatically when file is closed

### ISSUE THREAD

**Issue by posquit0** [neomake/neomake#842]
I want to close quickfix-list and location-list automatically when file is closed.
Just like in Syntastic plugin.

**Comment by wsdjeg** [comment]
here is my setting for qf:
```viml
    autocmd BufWinEnter quickfix nnoremap <silent> <buffer>
                \   q :cclose<cr>:lclose<cr>
    autocmd BufEnter * if (winnr('$') == 1 && &buftype ==# 'quickfix' ) |
                \   bd|
                \   q | endif

```

**Comment by blueyed** [comment]
Currently it is all more or less custom.
Somebody would have to start working on https://github.com/neomake/neomake/projects/1.. ;)

Consider looking at https://github.com/romainl/vim-qf and/or some custom/generic quickfix/loclist handling, since it should not really be specifc to a linter after all.
(e.g. I have something to automatically adjust the size of the windows, but also close them when they are empty - you can use the `NeomakeFinished` autocommand/hook for that)

Also it's not clear to me what Syntastic does: if you close window 1, where window 2 is its location list, and there are more windows, the location list gets closed also?  This is what `vim-qf` handles for me.

**Comment by posquit0** [comment]
@wsdjeg Thanks! However, it doesn't close quick fix list when there are two more windows.

@blueyed Wow, [vim-qf](https://github.com/romainl/vim-qf) is great. However, I found a strange behavior of vim-qf. When I have 2 windows in Vim and run a linter for each window, each window has to their quick-fix list in their window like below.

     Win 1             |         Win2
----------------|------------------ 
     QF1               |        QF2

However, the result is different like following when I use vim-qf :(

     Win 1             |         Win2
----------------|------------------ 
                       QF1  
-----------------------------------
                      QF2

Is it a bug of vim-qf or an intended feature?

**Comment by posquit0** [comment]
Ah, I found the configuration of vim-qf for my intention! Awesome plugin!
```vim
let g:qf_loclist_window_bottom=0
```
Thanks a lot!
