### ISSUE TITLE
:NeomakeFile!

### ISSUE THREAD

**Issue by bounceme** [neomake/neomake#973]
to run `:lmake` equivalent would be most intuitive to me

**Comment by blueyed** [comment]
But then also the `!` should behave like with `:[l]make` maybe after all?!

> If [!] is not given the first error is jumped to.

Given that `!` currently makes `:Neomake` behave differently (file vs. project) it seems a bit confusing.

**Comment by tweekmonster** [comment]
> Given that ! currently makes :Neomake behave differently (file vs. project) it seems a bit confusing.

How about `:Neomake !` then?  Then to make `:Neomake!` open in a location list, use `:Neomake! !`.  And to run `:Neomake` in all windows simultaneously, use `:Neomake! !!!`  😀

But seriously, maybe `:Neomake` could parse simple flags?  Like, `:Neomake! -l`.  I don't really like the `:NeomakeFile` name because it sounds too close to `Makefile`.  It doesn't make me think "run project but display in loclist".

**Comment by blueyed** [comment]
Closing it for now.
